version: '3.7'
services:

# service -> image -> container_name -> environment -> env_file -> port -> volumes -> restart

  ################## HADOOP ##################
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    environment:
      - CLUSTER_NAME=data_lake
    env_file:
      - ./hadoop-hive.env
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    restart: unless-stopped

  datanode0:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode0
    hostname: datanode0
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop-hive.env
    volumes:
      - hadoop_datanode0:/hadoop/dfs/data
    restart: unless-stopped

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    hostname: datanode1
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop-hive.env
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    restart: unless-stopped

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    hostname: datanode2
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop-hive.env
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    restart: unless-stopped

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    hostname: resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode0:9864 datanode1:9864 datanode2:9864"
    env_file:
      - ./hadoop-hive.env
    ports:
      - "8089:8088"
    restart: unless-stopped

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    hostname: nodemanager
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode0:9864 datanode1:9864 datanode2:9864 resourcemanager:8088"
    env_file:
      - ./hadoop-hive.env
    restart: unless-stopped
  
  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    hostname: historyserver
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode0:9864 datanode1:9864 datanode2:9864 resourcemanager:8088"
    env_file:
      - ./hadoop-hive.env
    ports:
      - "8188:8188"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    restart: unless-stopped

  
  ################# HIVE ##################
  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    hostname: hive-server
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    env_file:
      - ./hadoop-hive.env
    ports:
      - "10000:10000"
    volumes:
      - hive-data:/opt/hive
      - ./atlas/hive/atlas-application.properties:/opt/hive/conf/atlas-application.properties
      - ./atlas/hive/hive-site.xml:/opt/hive/conf/hive-site.xml
      - ./atlas/hive/hive-env.sh:/opt/hive/conf/hive-env.sh
      - ./atlas/hive/atlas-hive-hook:/opt/atlas-hive-hook
    restart: unless-stopped
    depends_on:
      - hive-metastore

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    hostname: hive-metastore
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode0:9864 datanode1:9864 datanode2:9864 hive-metastore-postgresql:5432"
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    ports:
      - "9083:9083"
    volumes:
      - hive-metastore-data:/opt/hive
    restart: unless-stopped
    depends_on:
      - hive-metastore-postgresql

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore-postgresql
    hostname: hive-metastore-postgresql
    volumes:
      - hive-metastore-postgresql-data:/var/lib/postgresql/data
    restart: unless-stopped
    depends_on:
      - namenode
      - datanode0
      - datanode1
      - datanode2


  ################## ZOOKEEPER ##################
  zookeeper:
    image: bitnami/zookeeper:3.5
    container_name: zookeeper
    hostname: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/bitnami/zookeeper


  ################## NIFI ##################
  nifi0:
    image: apache/nifi:1.26.0
    container_name: nifi0
    hostname: nifi0
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
      - NIFI_SENSITIVE_PROPS_KEY=MySuperSecretKey
    ports:
      - "6980:8080"
    volumes:
      - nifi0_data:/opt/nifi/nifi-current/flowfile_repository
      - nifi0_data:/opt/nifi/nifi-current/content_repository
      - nifi0_data:/opt/nifi/nifi-current/database_repository
      - nifi0_data:/opt/nifi/nifi-current/provenance_repository
      - ./conf/hadoop-3.2.1/core-site.xml:/opt/nifi/nifi-current/hadoop-3.2.1/core-site.xml
      - ./conf/hadoop-3.2.1/hdfs-site.xml:/opt/nifi/nifi-current/hadoop-3.2.1/hdfs-site.xml
    restart: unless-stopped
    depends_on:
      - zookeeper

  nifi1:
    image: apache/nifi:1.26.0
    container_name: nifi1
    hostname: nifi1
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
      - NIFI_SENSITIVE_PROPS_KEY=MySuperSecretKey
    ports:
      - "6979:8080"
    volumes:
      - nifi1_data:/opt/nifi/nifi-current/flowfile_repository
      - nifi1_data:/opt/nifi/nifi-current/content_repository
      - nifi1_data:/opt/nifi/nifi-current/database_repository
      - nifi1_data:/opt/nifi/nifi-current/provenance_repository
      - ./conf/hadoop-3.2.1/core-site.xml:/opt/nifi/nifi-current/hadoop-3.2.1/core-site.xml
      - ./conf/hadoop-3.2.1/hdfs-site.xml:/opt/nifi/nifi-current/hadoop-3.2.1/hdfs-site.xml
    restart: unless-stopped
    depends_on:
      - zookeeper

  nifi2:
    image: apache/nifi:1.26.0
    container_name: nifi2
    hostname: nifi2
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
      - NIFI_SENSITIVE_PROPS_KEY=MySuperSecretKey
    ports:
      - "6978:8080"
    volumes:
      - nifi2_data:/opt/nifi/nifi-current/flowfile_repository
      - nifi2_data:/opt/nifi/nifi-current/content_repository
      - nifi2_data:/opt/nifi/nifi-current/database_repository
      - nifi2_data:/opt/nifi/nifi-current/provenance_repository
      - ./conf/hadoop-3.2.1/core-site.xml:/opt/nifi/nifi-current/hadoop-3.2.1/core-site.xml
      - ./conf/hadoop-3.2.1/hdfs-site.xml:/opt/nifi/nifi-current/hadoop-3.2.1/hdfs-site.xml
    restart: unless-stopped
    depends_on:
      - zookeeper


  ################## SPARK ##################
  spark-master:
    image: bde2020/spark-master:3.2.1-hadoop3.2
    container_name: spark-master
    hostname: spark-master
    environment:
      - INIT_DAEMON_STEP=setup_spark
    ports:
      - "8090:8080"
      - "7077:7077"
      - "4040:4040"
    restart: unless-stopped

  spark-worker-0:
    image: bde2020/spark-worker:3.2.1-hadoop3.2
    container_name: spark-worker-0
    hostname: spark-worker-0
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    ports:
      - "3081:8081"
    restart: unless-stopped
    depends_on:
      - spark-master

  spark-worker-1:
    image: bde2020/spark-worker:3.2.1-hadoop3.2
    container_name: spark-worker-1
    hostname: spark-worker-1
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    ports:
      - "3082:8081"
    restart: unless-stopped
    depends_on:
      - spark-master

  spark-worker-2:
    image: bde2020/spark-worker:3.2.1-hadoop3.2
    container_name: spark-worker-2
    hostname: spark-worker-2
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    ports:
      - "3083:8081"
    restart: unless-stopped
    depends_on:
      - spark-master

  spark-history-server:
    image: bde2020/spark-history-server:3.2.1-hadoop3.2
    container_name: spark-history-server
    hostname: spark-history-server
    ports:
      - "18081:18081"
    volumes:
      - /tmp/spark-events-local:/tmp/spark-events
    restart: unless-stopped
    depends_on:
      - spark-master


  ################## SUPERSET ##################
  superset:
    image: apache/superset
    container_name: superset
    hostname: superset
    environment:
      SUPERSET_SECRET_KEY: datalake#2024
    ports:
      - "9038:8088"
    volumes:
      - superset_data:/app/superset_home
    restart: unless-stopped


  # ################## ATLAS ##################
  # atlas-server:
  #   build: 
  #     context: ./atlas/atlas
  #     # network: host
  #   image: lucasmsp/atlas:2.3
  #   container_name: atlas-server
  #   hostname: atlas-server
  #   ports:
  #     - "21000:21000"
  #   volumes:
  #     - ./atlas/atlas/resources/1000-Hadoop:/opt/atlas/models/1000-Hadoop
  #   depends_on:
  #     - kafka0
  #     - kafka1
  #     - kafka2
  #     - hive-metastore


  ################## KAFKA ##################
  kafka0:
    image: wurstmeister/kafka
    container_name: kafka0
    hostname: kafka0
    environment:
      # KAFKA_CREATE_TOPICS: "create_events:1:1,delete_events:1:1,ATLAS_HOOK:1:1"
      KAFKA_ADVERTISED_HOST_NAME: kafka0
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      JMX_PORT: 9090
    depends_on:
      - zookeeper 
    volumes:
      - kafka0_data:/kafka/kafka-logs-kafka0

  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    hostname: kafka1
    environment:
      # KAFKA_CREATE_TOPICS: "create_events:1:1,delete_events:1:1,ATLAS_HOOK:1:1"
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      JMX_PORT: 9090
    depends_on:
      - zookeeper 
    volumes:
      - kafka1_data:/kafka/kafka-logs-kafka1

  kafka2:
    image: wurstmeister/kafka
    container_name: kafka2
    hostname: kafka2
    environment:
      KAFKA_CREATE_TOPICS: "create_events:3:3,delete_events:3:3,ATLAS_HOOK:3:3"
      KAFKA_ADVERTISED_HOST_NAME: kafka2
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      JMX_PORT: 9090
    depends_on:
      - zookeeper  
      - kafka0
      - kafka1
    volumes:
      - kafka2_data:/kafka/kafka-logs-kafka2

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    hostname: kafka-ui
    ports:
      - "8079:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: data-lake
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka0:9092,kafka1:9092,kafka2:9092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9090
      DYNAMIC_CONFIG_ENABLED: 'true'
    restart: unless-stopped
    depends_on:
      - kafka0
      - kafka1
      - kafka2


volumes:
  hadoop_namenode:
  hadoop_datanode0:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_historyserver:
  hive-data:
  hive-metastore-data:
  hive-metastore-postgresql-data:
  zookeeper_data:
  nifi0_data:
  nifi1_data:
  nifi2_data:
  superset_data:
  kafka0_data:
  kafka1_data:
  kafka2_data: